name: portfolio-v2

services:
  client:
    container_name: client
    build: ./app/client
    working_dir: /app
    volumes:
      - ./app/client:/app
      - /app/node_modules
    ports:
      - "${CLIENT_PORT:-5173}:5173"
  api:
    container_name: api
    build: ./app/api
    working_dir: /app
    volumes:
      - ./app/api:/app
      - /app/node_modules
    ports:
      - "${API_PORT:-3000}:3000"
      - ${DEBUG_PORT:-9229}:9229
  scheduler:
    container_name: scheduler
    build: ./app/scheduler
    working_dir: /app
    volumes:
      - ./app/scheduler:/app
      - /app/node_modules
