name: portfolio-v2

services:
  client:
    container_name: client
    build: ./client
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "${CLIENT_PORT:-5173}:5173"
    environment:
      VITE_CLIENT_PORT: ${CLIENT_PORT:-5173}
      # VITE_WEBSOCKET_URL: ws://api:${WEBSOCKET_PORT:-3000}
  api:
    container_name: api
    build: ./api
    working_dir: /app
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "${API_PORT:-3000}:3000"
      - ${DEBUG_PORT:-9229}:9229
    environment:
      EXPRESS_API_PORT: ${API_PORT:-3000}
  scheduler:
    container_name: scheduler
    build: ./scheduler
    working_dir: /app
    volumes:
      - ./scheduler:/app
      - /app/node_modules
    # environment:
    #   REDIS_HOST: ${REDIS_HOST:-redis}
    #   REDIS_PORT: ${REDIS_PORT:-6379}
  # depends_on:
  #   - redis
  # redis:
  #   container_name: redis
  #   image: redis:7.4-alpine
  #   ports:
  #     - "${REDIS_PORT:-6379}:6379"
  #   command: redis-server
