name: Secrets
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Run Go File
        env:
          DB_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
          DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
            go run server/main.go
